name: CI/CD for NestJS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Set Permissions for Nest CLI
        run: chmod +x ./node_modules/.bin/nest

      - name: Run Build
        run: npx nest build

      - name: Build Docker Image
        run: |
          docker build -t nestjs-hola-mundo .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag nestjs-hola-mundo ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-hola-mundo:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-hola-mundo:latest
